### ISSUE TITLE
[Leetcode] 344. Reverse String

### ISSUE THREAD

**Issue by ASak1104** [spring-comes-to-us/algorithm-comes-to-us#14]
## [문제 링크](https://leetcode.com/problems/reverse-string/)

<img width="802" alt="image" src="https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/31983961/25f9ae6a-24e4-45f1-8f1a-65dc073e8e1f">

**Comment by uijin-j** [comment]
### 344. Reverse String
- Language : Java
- 성능
🌟 시간: 0ms, 메모리: 50.19MB 🌟

### 코드 풀이
```java
class Solution {
    public void reverseString(char[] s) {
        int len = s.length;

        for(int i = 0; i < len / 2; ++i) {
            char temp = s[i];
            s[i] = s[len - 1 - i];
            s[len - 1 - i] = temp;
        }
    }
}
```

**Comment by shoeone96** [comment]
### 344. Reverse String
- Language : Java
- 성능
🌟 메모리: 51.4MB, 시간: 0ms 🌟
코드 풀이
```
class Solution {
    static char temp;
    public void reverseString(char[] s) {
        for (int i = 0; i < s.length / 2; i++) {
            temp = s[i];
            s[i] = s[s.length - 1 - i];
            s[s.length -1 - i] = temp;
        }
    }
}
```

**Comment by ASak1104** [comment]
### 344. Reverse String
- Language : Kotlin
- 성능 : Time: 214 ms (91.42%), Space: 44.9 MB (70.34%)

### [코드 풀이](https://github.com/ASak1104/code2self/blob/main/LeetCode/Easy/0344-reverse-string/0344-reverse-string.kt)
```kt
class Solution {

    fun reverseString(s: CharArray): Unit {
        val mid = s.size ushr 1

        for (i in 0 until mid) {
            swap(s, i, s.lastIndex - i)
        }
    }
    
    inline fun swap(s: CharArray, left: Int, right: Int) {
        val temp = s[left]
        
        s[left] = s[right]
        s[right] = temp
    }
}
```

### 코멘트
- `s.size ushr 1`은 자바에서 `s.size() >>> 1`과 똑같은 의미예요!

**Comment by Sehee-Lee-01** [comment]
<img width="626" alt="image" src="https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/85275893/14754bf0-3b20-4c60-83b9-0e9dbda17cf9">

<img width="632" alt="image" src="https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/85275893/e653c4fa-ea70-47b6-88b5-6c0a9e2526e5">

## 코멘트
- 아래 주석 부분 있을 때랑 없을 때랑 시간 차가  자주 쓰이는 필요한 값만 변수처리 해야겠어용!

## 코드 풀이
```java
class Solution {
    public void reverseString(char[] s) {
        // int halfCnt = s.length / 2;
        for (int i = 0; i < s.length / 2; i++) {
            char tmp = s[i];
            s[i] = s[s.length - 1 - i];
            s[s.length - 1 - i] = tmp;
        }
    }
}
```

**Comment by yenzip** [comment]
### 344. Reverse String

- Language: [**C++**](https://github.com/yenzip/problem-solving/commit/69e13c1411a5cd1ccece14a8988761b660386e37), **JAVA**
- 성능: [**C++**] Time: 19ms, Memory: 23.7MB, [**JAVA**] Time: 1ms, Memory: 50.7MB
<br/>

### 코드 풀이
``` java
class Solution {
    public void reverseString(char[] s) {
        int len = s.length;

        for(int i = 0; i < len / 2; i++) {
            char tmp = s[i];
            s[i] = s[len - i - 1];
            s[len - i - 1] = tmp;
        }
    }
}
```
<br/>

### 코멘트

- C++은 swap이라는 메서드가 있는데, JAVA는 직접 구현해줘야 하는군요!
