### ISSUE TITLE
[LeetCode] 240. Search a 2D Matrix II

### ISSUE THREAD

**Issue by Sehee-Lee-01** [spring-comes-to-us/algorithm-comes-to-us#53]
## [문제링크](https://leetcode.com/problems/search-a-2d-matrix-ii/description/)
- 기한: ~ 1월 25일 목요일

![image](https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/85275893/72a78b80-51f9-457a-894c-a3708fd97862)

![image](https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/85275893/978e9620-43e1-4d62-af04-df8ca38a7757)

**Comment by uijin-j** [comment]
### 240. Search a 2D Matrix II
- Language : Java
- 성능
🌟 시간: 6 ms (Beats 47.99%), 메모리: 46.14 MB (Beats 49.71%) 🌟


<details>
<summary><h3>코드 풀이</h3></summary>

```java
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        for(int i = 0; i < matrix.length; ++i) {
            if(matrix[i][0] > target) return false; 
            int index = binarySearch(target, matrix[i]);
            if(index != -1) return true;
        }

        return false;
    }

    public int binarySearch(int target, int[] arr) {
        int left = 0, right = arr.length - 1;

        while(left <= right) {
            int mid = (left + right) / 2;

            if(arr[mid] > target) {
                right = mid - 1;
            } else if (arr[mid] < target) {
                left = mid + 1;
            } else {
                return mid;
            }
        }

        return -1;
    }
}
```
</details>

### 코멘트
- 이진 탐색을 여러번 썼는데요! 행뿐만 아니라 컬럼(세로)도 정렬이 되어 있는데 이 조건을 조금 더 잘 쓸 순 없을지 고민해 봐야겠네요.!

**Comment by Sehee-Lee-01** [comment]
<img width="534" alt="image" src="https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/85275893/4106cf93-00a7-41fc-a793-b7820afe837e"> 

## Comment
- 처음에 이진 탐색으로 풀려다가 가로, 세로를 모두 이용하는 이진 탐색 방법이 있는지, 혹시 구역을 나눠서 이진탐색을 하는 것인지 방법론을 생각하다가 끝끝내 생각이 나지 않아 다른 분들의 풀이를 힌트삼아 살짝보고 로직 생각해서 풀어봤습니다!
- 저의 풀이는 이진 탐색 풀이는 아닌 것 같지만 **볼 필요가 없는 구간은 탐색하지 않는 로직**은 이진 탐색과 비슷합니다. 

<details>
<summary><h2>Code</h2></summary>

```java
class Solution {
    static int m, n;

    public boolean searchMatrix(int[][] matrix, int target) {
        m = matrix.length;
        n = matrix[0].length;

        int row = 0;
        int col = n-1;
        while(row < m && col >= 0) {
            if (matrix[row][col] == target) {
                return true;
            }

            if (matrix[row][col] < target) {
                row++;
            } else {
                col--;
            }
        }
        return false;
    }
}

```

</details>

**Comment by ASak1104** [comment]
### 240. Search a 2D Matrix II

- 언어 : Java, Kotlin
- 코드 : [깃허브](https://github.com/ASak1104/code2self/tree/main/LeetCode/Medium/0240-search-a-2d-matrix-ii)
- 성능
  - Java : Time: 6 ms (47.99%), Space: 45.9 MB (77.34%)
  - Kotlin : Time: 265 ms (29.09%), Space: 44 MB (25.45%)

<details>
<summary><h3>Java 풀이</h3></summary>

```java
class Solution {

    public boolean searchMatrix(int[][] matrix, int target) {
        for (int[] row : matrix) {
            if (search(row, target)) {
                return true;
            }
        }

        return false;
    }

    boolean search(int[] row, int target) {
        int left = 0;
        int right = row.length - 1;

        while (left <= right) {
            int mid = (left + right) >>> 1;
            int value = row[mid];

            if (value == target) {
                return true;
            }

            if (value < target) {
                left = mid + 1;
            } else {
                right = mid - 1;
            }
        }

        return false;
    }

}

```

</details>

<details>
<summary><h3>Kotlin 풀이</h3></summary>

```kt
class Solution {

    fun searchMatrix(matrix: Array<IntArray>, target: Int): Boolean {
        var r = 0
        var c = matrix.first().lastIndex

        while (r < matrix.size && c >= 0) {
            if (matrix[r][c] == target) {
                return true
            }

            if (matrix[r][c] < target) {
                r++
            } else {
                c--
            }
        }

        return false
    }
}

```

</details>

### 코멘트

- 여러가지 방법으로 접근을 해봤는데 기본적인 이진탐색보다 성능이 좋지 않네요
- 컬럼에 대한 정렬을 잘 살린 풀이가 있는지 찾아봤는데
- 우측 상단부터 시작하는 탐색 방법과 $O(N + M)$
- divide and conquer 풀이가 있더라고요 $O(M*N)$
- 사실 우측 상단 탐색을 제외한 다른 풀이에서는 장점을 살리기 힘든 것 같아요

**Comment by shoeone96** [comment]
### 240. Search a 2D Matrix II
- Language : Java
- 성능
<img width="695" alt="스크린샷 2024-01-26 오전 12 36 53" src="https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/85065626/37d1da69-c80a-4d22-a8ee-66d8a96a3193">


<details>
<summary><h3>코드 풀이</h3></summary>

```java
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        for (int i = 0; i < matrix.length; i++) {
            int left = 0;
            int right = matrix[i].length - 1;
            while (left <= right) {
                int mid = left + (right - left) / 2;
                if (matrix[i][mid] > target) {
                    right = mid - 1;
                } else if (matrix[i][mid] < target) {
                    left = mid + 1;
                } else {
                    return true;
                }
            }
        }
        return false;
    }
}

```
</details>

### 코멘트
- 뭔가 특별한 방법이 있을 것 같긴 한데 일단 위에서부터 행마다 이진 탐색을 이용해 풀었습니다

**Comment by yenzip** [comment]
### 240. Search a 2D Matrix II
- Language : JAVA
- 성능
**이진 탐색**
![image](https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/87412097/38fcf5e9-7f47-4163-9693-c149ae1fe1ca)
**이진 탐색 사용 X**
![image](https://github.com/spring-comes-to-us/algorithm-comes-to-us/assets/87412097/213491fe-9caa-4453-97dd-191505889e88)


<details>
<summary><h3>이진 탐색 코드 풀이</h3></summary>

```java
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        int n = matrix.length;
        int m = matrix[0].length;
        
        for(int row = 0; row < n; row++) {
            int left = 0;
            int right = m - 1;

            while(left <= right) {
                int mid = left + (right - left) / 2;

                if(matrix[row][mid] == target) {
                    return true;
                } else if(matrix[row][mid] < target) {
                    left = mid + 1;
                } else {
                    right = mid - 1;
                }
            }
        }

        return false;
    }
}

```
</details>

<details>
<summary><h3>이진 탐색을 사용하지 않은 코드 풀이</h3></summary>

```java
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        int n = matrix.length;
        int m = matrix[0].length; 

        int row = 0;
        int col = m - 1;
        
        while(row < n && col >= 0) {
            if(matrix[row][col] == target) {
                return true;
            } else if (matrix[row][col] < target) {
                row++;
            } else {
                col--;
            }
        }

        return false;
    }
}


```
</details>


### 코멘트
- 행을 순회하며 이진 탐색을 진행해 문제를 해결했습니다!
- 이진 탐색을 사용하지 않은 경우, [0, m - 1]인 왼쪽 아래에서부터 target 값과 비교하며 탐색했습니다.
- 이 문제가 코테에 나온다면, 이진 탐색보다는 한 모서리를 기준으로 탐색하는 2번째 풀이로 문제를 해결할 것 같아요!

**Comment by IjjS** [comment]
###  240. Search a 2D Matrix II

* 언어: 자바
* 성능: 7ms, 45.2MB

<details>
<summary><h3>코드 풀이</h3></summary>

```java
class Solution {
    public boolean searchMatrix(int[][] matrix, int target) {
        for (int[] array : matrix) {
            if (Arrays.binarySearch(array, target) >= 0) return true;
        }
        
        return false;
    }
}
```

</details>

### 코멘트
* 책을 보고 다른 풀이로 더 잘 풀 수 있다는 걸 알았습니다. 근데 처음 시도 했던 방법으로 올립니다!
